name: deploy-backend

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: famtree
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Install dependencies
      run: |
        go version
        go build
    # - name: 'Setup Cloud SDK'
    #   run: |
    #     echo "deb http://packages.cloud.google.com/apt cloud-sdk-jessie main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
    #     curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    #     sudo apt-get update && sudo apt-get install google-cloud-sdk
    # - name: 'Deploy to App Engine'
    #   run: |
    #     echo ${{ secrets.DEPLOY_KEY_FILE_PRODUCTION }} > keyfile.json
    #     gcloud version
    #     gcloud auth activate-service-account --key-file keyfile.json
    #     gcloud --quiet --project ${{ secrets.PROJECT_ID_PRODUCTION }} app deploy
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with: 
        credentials_json: ${{ secrets.DEPLOY_KEY_FILE_PRODUCTION }}
    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      # with:
      #   project_id: 'explago-kawoozy'
      #   service_account_key: ${{ secrets.DEPLOY_KEY_FILE_PRODUCTION }}
      #   export_default_credentials: true
    - name: Deploy
      uses: google-github-actions/deploy-appengine@v0
      with:
        deliverables: app.yaml
        version: v1